// Shared standard-field catalogue. Keys MUST match the property names on the
// backend's `StandardFieldsConfig` (generated by `declare_standard_fields!` in
// `crates/core/src/forms/mod.rs`).
//
// This is the single TS source — `apps/admin/src/lib/forms/standardFields.ts`
// re-exports it rather than keeping a second copy.

export interface StandardFieldDef {
  key: string;
  default_label: string;
  /** HTML input type when rendered as a normal text-style field. */
  input_type: "text" | "email" | "tel" | "url" | "textarea";
  autocomplete?: string;
}

export const STANDARD_FIELDS: readonly StandardFieldDef[] = [
  { key: "first_name", default_label: "First name", input_type: "text", autocomplete: "given-name" },
  { key: "last_name", default_label: "Last name", input_type: "text", autocomplete: "family-name" },
  { key: "email", default_label: "Email", input_type: "email", autocomplete: "email" },
  { key: "phone", default_label: "Phone", input_type: "tel", autocomplete: "tel" },
  { key: "company", default_label: "Company", input_type: "text", autocomplete: "organization" },
  { key: "job_title", default_label: "Job title", input_type: "text", autocomplete: "organization-title" },
  { key: "website", default_label: "Website", input_type: "url", autocomplete: "url" },
  { key: "message", default_label: "Message", input_type: "textarea" },
  { key: "address_line_1", default_label: "Address line 1", input_type: "text", autocomplete: "address-line1" },
  { key: "address_line_2", default_label: "Address line 2", input_type: "text", autocomplete: "address-line2" },
  { key: "city", default_label: "City", input_type: "text", autocomplete: "address-level2" },
  { key: "state", default_label: "State / region", input_type: "text", autocomplete: "address-level1" },
  { key: "postal_code", default_label: "Postal code", input_type: "text", autocomplete: "postal-code" },
  { key: "country", default_label: "Country", input_type: "text", autocomplete: "country-name" },
] as const;

export type StandardFieldKey = (typeof STANDARD_FIELDS)[number]["key"];

/**
 * ISO 3166-1 countries offered when a `country` field sets
 * `input_override: "select"`, and the choices a `country` custom field always
 * offers.
 *
 * The submitted value is the alpha-2 code. That needs no backend change:
 * `normalize_country` in the GoHighLevel backend already passes any two-letter
 * code straight through (upper-cased), and it is more reliable than the
 * name-matching it falls back to for free-text input.
 *
 * Re-exported from `regions.ts` — the list used to be a hand-written 46-entry
 * subset, which would now be a second, shorter country list in the same form
 * builder.
 */
export { COUNTRIES, type RegionOption, type RegionOption as CountryOption } from "./regions";
