#!/usr/bin/env node
// Generates the ISO 3166 catalogues consumed by BOTH the Rust core and the
// TypeScript renderer, from one vendored source, into two checked-in files.
//
// Two hand-maintained copies of a 3,590-row table is exactly the drift hazard
// CLAUDE.md warns about for `visibility.rs` / `visibility.ts`, so neither side
// is written by hand. Run this after refreshing `data/iso-codes/`, then commit
// the output; `pnpm gen:regions:check` asserts it is current.
//
//   node scripts/gen-regions.mjs
//
// Source: Debian iso-codes (LGPL-2.1), https://salsa.debian.org/iso-codes-team/iso-codes
//   data/iso_3166-1.json  — countries
//   data/iso_3166-2.json  — subdivisions
//
// Output is checked in so neither `cargo build` nor the embed build needs node
// or the network.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "data", "iso-codes");

const TS_OUT = join(ROOT, "packages", "form-renderer", "src", "regions.data.ts");
const RS_OUT = join(ROOT, "crates", "core", "src", "forms", "regions.json");

// Packing delimiters. Asserted absent from every name below — if ISO ever ships
// one of these in a name, this script fails loudly rather than emitting a table
// that silently mis-parses.
const DELIMITERS = /[~|:=]/;

/** Debian embeds an alternate name or code in trailing brackets: "Wales [Cymru GB-CYM]". */
function cleanName(name) {
  return name.replace(/\s*\[[^\]]*\]\s*$/, "").trim();
}

function read(file) {
  return JSON.parse(readFileSync(join(SRC, file), "utf8"));
}

function assertPackable(what, code, name) {
  if (DELIMITERS.test(name)) {
    throw new Error(`${what} ${code} name ${JSON.stringify(name)} contains a packing delimiter`);
  }
  if (!name) throw new Error(`${what} ${code} has an empty name`);
}

// ---------------------------------------------------------------------------
// Countries — ISO 3166-1 alpha-2, sorted by display name.
// `common_name` is the short form ("Bolivia" over "Bolivia, Plurinational State of").
// ---------------------------------------------------------------------------
const countries = read("iso_3166-1.json")["3166-1"]
  .map((c) => ({ code: c.alpha_2, name: cleanName(c.common_name || c.name) }))
  .sort((a, b) => a.name.localeCompare(b.name, "en"));

for (const c of countries) assertPackable("country", c.code, c.name);

// ---------------------------------------------------------------------------
// Subdivisions — ISO 3166-2, TOP LEVEL ONLY.
//
// Entries carrying a `parent` are nested one level down (GB's 200+ districts
// under England/Scotland/Wales/NI, France's departments under its regions).
// A "state / province" picker wants the top tier: 57 US states, 13 Canadian
// provinces, 4 UK countries — not a flat list mixing both tiers.
//
// The stored value is the bare subdivision code (`CA`), not the full ISO
// 3166-2 code (`US-CA`) — the country is captured by the sibling field, and
// CRMs expect the bare form. See the GoHighLevel backend, which forwards
// `state` verbatim.
// ---------------------------------------------------------------------------
const byCountry = new Map();
for (const s of read("iso_3166-2.json")["3166-2"]) {
  if (s.parent) continue;
  const country = s.code.slice(0, 2);
  const code = s.code.slice(3);
  const name = cleanName(s.name);
  assertPackable("subdivision", s.code, name);
  if (!byCountry.has(country)) byCountry.set(country, []);
  byCountry.get(country).push({ code, name });
}

const known = new Set(countries.map((c) => c.code));
for (const country of byCountry.keys()) {
  if (!known.has(country)) throw new Error(`subdivisions for unknown country ${country}`);
}

const subdivisionCountries = [...byCountry.keys()].sort();
for (const list of byCountry.values()) list.sort((a, b) => a.name.localeCompare(b.name, "en"));

// ---------------------------------------------------------------------------
// Pack.
//   countries:    "US:United States|CA:Canada"
//   subdivisions: "US=AL:Alabama|AK:Alaska~CA=AB:Alberta"
// ---------------------------------------------------------------------------
const packedCountries = countries.map((c) => `${c.code}:${c.name}`).join("|");
const packedSubdivisions = subdivisionCountries
  .map((cc) => `${cc}=${byCountry.get(cc).map((s) => `${s.code}:${s.name}`).join("|")}`)
  .join("~");

const subdivisionCount = [...byCountry.values()].reduce((n, l) => n + l.length, 0);
const banner = `// @generated by scripts/gen-regions.mjs from data/iso-codes — do not edit.
// Source: Debian iso-codes (LGPL-2.1). Regenerate with \`pnpm gen:regions\`.
// ${countries.length} countries; ${subdivisionCount} top-level subdivisions across ${subdivisionCountries.length} countries.`;

writeFileSync(
  TS_OUT,
  `${banner}

/** ISO 3166-1 alpha-2, name-sorted: \`"US:United States|CA:Canada"\`. */
export const PACKED_COUNTRIES =
  ${JSON.stringify(packedCountries)};

/**
 * ISO 3166-2 top-level subdivisions: \`"US=AL:Alabama|AK:Alaska~CA=AB:Alberta"\`.
 *
 * Not bundled into the embed script — it is ~40 KB gzipped and most forms have
 * no state field. The server sends it on \`PublicFormDto.regions\` only when a
 * form needs it; this copy exists for the admin preview, which has no such
 * constraint. See \`regions.ts\`.
 */
export const PACKED_SUBDIVISIONS =
  ${JSON.stringify(packedSubdivisions)};
`,
);

writeFileSync(
  RS_OUT,
  `${JSON.stringify({ countries: packedCountries, subdivisions: packedSubdivisions }, null, 2)}\n`,
);

console.log(
  `regions: ${countries.length} countries, ${subdivisionCount} subdivisions across ` +
    `${subdivisionCountries.length} countries\n` +
    `  ${TS_OUT.replace(ROOT + "/", "")}\n  ${RS_OUT.replace(ROOT + "/", "")}`,
);
